project:
  type: book
  output-dir: docs
  

book:
  title: "Workspace"
  # navbar:
  #   background: primary
  #   search: true
  #   left:
  #     - href: src/index.qmd
  #       text: Home
  #     - href: src/about.qmd
  #       text: About
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  reader-mode: true
  repo-url: https://github.com/hashcx/workspace/
  downloads: [pdf]
  
  chapters: 
    - index.qmd
    
    - part: src/notebooks/_notebooks.qmd
      chapters: 
        - src/notebooks/r.qmd
        - src/notebooks/quarto.qmd
        - src/notebooks/rstudio.qmd
        - src/notebooks/windows.qmd
    
    - part: src/r-for-data-science/_r-for-data-science.qmd
      chapters: 
      - src/r-for-data-science/01-data-viz.qmd
      - src/r-for-data-science/02-workflow-basics.qmd
      - src/r-for-data-science/03-data-trans.qmd
      - src/r-for-data-science/04-workflow-code-style.qmd
      - src/r-for-data-science/05-data-tidying.qmd
      - src/r-for-data-science/06-workflow-scripts-and-projects.qmd
      - src/r-for-data-science/07-data-import.qmd
    
    - part: src/practice/_practice.qmd
      chapters: 
        - src/practice/topic-modeling-r.qmd

format:
  html:
    theme: cosmo
    css: sty/styles.css
    toc: true
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-tools: true
  pdf:
    documentclass: scrreprt
    keep-tex: true

execute:
  cache: true
  freeze: auto

