project:
  type: website
  output-dir: docs
  

website:
  title: "Notebooks"
  navbar:
    title: true
    background: primary
    search: true
    left:
      - href: src/index.qmd
        text: Home
      - href: src/about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com
  sidebar: 
    style: docked
    search: true
    contents: 
      - section: "R"
      - contents:
        - src/r-basics.qmd
      - section: "Python"
      - contents:
        - src/index.qmd

format:
  html:
    theme: cosmo
    css: sty/styles.css
    toc: true

editor: visual

