project:
  type: website
  output-dir: docs
  

website:
  title: "R Notebook"
  navbar:
    left:
      - href: src/index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

