project:
  type: website
  output-dir: docs
  

website:
  title: "Notebooks"
  navbar:
    title: true
    background: primary
    search: true
    left:
      - href: src/index.qmd
        text: Home
      - href: src/about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com
  sidebar: 
    contents: auto

format:
  html:
    theme: cosmo
    css: sty/styles.css
    toc: true

editor: visual

