# Code Files

It is advisable to perform the following step at the beginning of each code file.  The example code chunks are for the R programming language.

## 1. Create Project

When wanting to write R code, create a project then add R/Rmd/qmd files into it instead of only creating a single file. This will allow saving the workspace settings.



## 2. Clean Workspace

Always start by clearing the workspace to ensure objects created in other files are not used in the current file by using the code shown blew.  This can be done manually in RStudio: Environment window -> Broom icon.

```r
#| include: false

rm(list = ls())
```


## 3. Insall & Load Packages Automatically

Although people may not like installing packages on their machines automatically for different reasons, I prefer this route for myself because I use multiple machines and installing packages one at a time (when the code breaks multiple times, one for each missing package) is annoying.

Step 1: Store all needed packages to a variables by including the following code chunk and changing the given list of sample packages.

```r
#| include: false

packages <- c("here", "tidyverse", "janitor")
```


Step 2: Install missing packages automatically, if any, by including the following code chunk as it is.

```r
#| include: false

install.packages(setdiff(packages, rownames(installed.packages())))

```

Step 3: Load packages in one go automatically by including the following code chunk as it is.


```r
#| include: false

lapply(packages, require, character.only = TRUE)
```


::: callout-note
### Execution Options

The above R code chunk includes the execution option `#| include: false` which will prevent any output from being included in the knitted/rendered document.  For the complete list of execution options that can be used in Quarto files see [this page (html)](https://quarto.org/docs/computations/execution-options.html).

:::
