## Exploartory Data Analysis

For each dataset, try to obtain the following Exploartory Data Analysis (EDA) summaries.

### Manual Summaries

using the dataset codebook, if available, or via some search and/or asking, answer the following questions:

- What is its source?
- How it was obtained? 
- Who collected it?
- When it was collected?
- What does each column/variable represent?
- What does each row/observation represent?

### Computational Summaries

Through computations, ie, code, answer the following questions:

- How many columns/variables?
- How many rows/observations?
- What is the data type of each column/variable?
- What are the top few rows/observations?
- What are the bottom few rows/observations?
- How many missing values in each column/variable?
- How many rows/observations contain 1+ missing values?
- What is the summary statistics of each column/variable?

[In a blog post (html)](https://m-clark.github.io/exploratory-data-analysis-tools/), Michael Clark demos eight R packages that can help explore data quickly and effectively.
The demoed packages are: 

- [arsenal](https://mayoverse.github.io/arsenal/)
- [DataExplorer](https://boxuancui.github.io/DataExplorer/)
- [dataReporter](https://github.com/ekstroem/dataReporter) ([dataMaid](https://github.com/ekstroem/dataMaid?tab=readme-ov-file) previously)
- [gtsummary](https://www.danieldsjoberg.com/gtsummary/)
- [janitor](https://sfirke.github.io/janitor/)
- [SmartEDA](https://daya6489.github.io/SmartEDA/index.html)
- [summarytools](https://github.com/dcomtois/summarytools)
- [visdat](https://docs.ropensci.org/visdat/).
